
<?php include ('inc/header.php');?>

<!--Inner Banner Section Start-->
<div class="tj-inner-banner" style="background:url('images/inner-banner-2.jpg') top center no-repeat">
	<div class="container">
		<h2>Terms & Conditions</h2>
	</div>
</div>
<!--Inner Banner Section End-->

<!--Breadcrumb Section Start-->
<div class="tj-breadcrumb">
	<div class="container">
		<ul class="breadcrumb-list">
			<li><a href="home-1.html">Home</a></li>
			<li class="active">Terms & Conditions</li>
		</ul>
	</div>
</div>
<!--Breadcrumb Section End-->	

<!--Welcome Section Content Start-->
<section class="tj-welcome">
	<div class="container">
		<div class="row">
			<!--Welcome Section Start-->
			<div class="col-md-offset-2 col-md-8 col-sm-7">
				<div class="about-info">
					<p>
						<b>Last Updated: May 6, 2022</b><br>
						These Terms of Service constitute a legally binding agreement (the “Agreement”) between you and Saferide Technologies, Inc., its parents, subsidiaries, representatives, affiliates, officers and directors (collectively, “Saferide Technologies,” “we,” “us” or “our”) governing your use of the Saferide Technologies application (the “Saferide Technologies App”), website, and technology platform (collectively, the “Saferide Technologies Platform”).
						By entering into this Agreement, and/or by using or accessing the Saferide Technologies Platform you expressly acknowledge that you understand this Agreement (including the dispute resolution and arbitration provisions in Section 17) and accept all of its terms. IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOU MAY NOT USE OR ACCESS THE SAFERIDE TECHNOLOGIES PLATFORM OR ANY OF THE SERVICES PROVIDED THROUGH THE SAFERIDE TECHNOLOGIES PLATFORM. If you use the Saferide Technologies Platform in another country, you agree to be subject to Saferide Technologies' terms of service for that country.<br><br>

						When using the Saferide Technologies Platform, you also agree to conduct yourself in accordance with our Community Guidelines, which shall form part of this Agreement between you and Saferide Technologies.<br><br>

						<b>1. The Saferide Technologies Platform</b><br>
						The Saferide Technologies Platform provides a marketplace where, among other things, persons who seek transportation to certain destinations (“Riders”) can be matched with transportation options to such destinations. One option for Riders is to request a ride from rideshare drivers who are driving to or through those destinations (“Drivers”). Drivers and Riders are collectively referred to herein as “Users,” and the driving services provided by Drivers to Riders shall be referred to herein as “Rideshare Services.” As a User, you authorize Saferide Technologies to match you with Drivers or Riders based on factors such as your location, the requested pickup location, the estimated time to pickup, your destination, User preferences, driver mode, and platform efficiency, and to cancel an existing match and/or rematch you with a Driver or Rider based on the same considerations. Any decision by a User to offer or accept Rideshare Services is a decision made in such User’s sole discretion. Each Rideshare Service provided by a Driver to a Rider shall constitute a separate agreement between such persons.<br><br>

						<b>2.0 Modification to the Agreement</b><br>
						Saferide Technologies reserves the right to modify the terms and conditions of this Agreement, and such modifications shall be binding on you only upon your acceptance of the modified Agreement. Saferide Technologies reserves the right to modify any information on pages referenced in the hyperlinks from this Agreement from time to time, and such modifications shall become effective upon posting. Continued use of the Saferide Technologies Platform or Rideshare Services after any such changes shall constitute your consent to such changes. Unless material changes are made to the arbitration provisions herein, you agree that modification of this Agreement does not create a renewed opportunity to opt out of arbitration (if applicable).<br><br>

						<b>3.0 Eligibility</b><br>
						The Saferide Technologies Platform may only be used by individuals who have the right and authority to enter into this Agreement and are fully able and competent to satisfy the terms, conditions, and obligations herein. The Saferide Technologies Platform is not available to Users who have had their User account temporarily or permanently deactivated. You may not allow other persons to use your User account, and you agree that you are the sole authorized user of your account. To use the Saferide Technologies Platform, each User shall create a User account. Each person may only create one User account, and Saferide Technologies reserves the right to deactivate any additional or duplicate accounts. Your participation in certain Saferide Technologies programs and use of certain Saferide Technologies products or services may be subject to additional eligibility requirements as determined by Saferide Technologies.<br><br>

						<b>4.0 Charges</b><br>
						As a Rider, you understand that request or use of Rideshare Services may result in charges to you (“Charges”). Charges for Rideshare Services include Fares and other applicable fees, tolls, surcharges, and taxes as set forth on your market’s Saferide Technologies page, plus any tips to the Driver that you elect to pay. Saferide Technologies has the authority and reserves the right to determine and modify pricing by posting applicable pricing terms to your market’s Saferide Technologies page or quoting you a price for a specific ride at the time you make a request. Pricing may vary based on the type of service you request (e.g., shared, economy, extra seats, luxury) as described on your market’s Saferide Technologies page. You are responsible for reviewing the applicable Saferide Technologies page or price quote within the Saferide Technologies App and shall be responsible for all Charges incurred under your User account regardless of your awareness of such Charges or the amounts thereof.<br><br>

						<b>4.1 Fares. There are two types of Fares, variable and quoted.</b><br>
						- Variable Fares. Variable fares consist of a base charge and incremental charges based on the duration and distance of your ride. For particularly short rides, minimum fares may apply. Please note that we use GPS data from your Driver’s phone to calculate the distance traveled on your ride. We cannot guarantee the availability or accuracy of GPS data. If we lose signal we will calculate time and distance using available data from your ride.
						- Quoted Fares. In some cases Saferide Technologies may quote you a Fare at the time of your request. The quote is subject to change until the ride request is confirmed. If during your ride you change your destination, make multiple stops, or attempt to abuse the Saferide Technologies Platform, we may cancel the fare quote and charge you a variable fare based on the time and distance of your ride. Saferide Technologies does not guarantee that the quoted fare price will be equal to a variable fare for the same ride. Quoted Fares may include the Fees and Other Charges below, as applicable.<br><br>
						
						<b>4.2 Fees and Other Charges.</b><br>
						- Service Fee. You may be charged a “Service Fee” for each ride as set forth on the applicable Saferide Technologies Cities page.
						- Prime Time. At certain times, including times of high demand for Rideshare Services (“Prime Time”), you acknowledge that Charges may increase substantially. For all rides with a variable fare, we will use reasonable efforts to inform you of any Prime Time increases in effect at the time of your request. For Quoted Fares we may factor in the Prime Time increases into the quoted price of the ride.
						- Cancellation Fee. After requesting a ride you may cancel it through the Saferide Technologies App, but note that in certain cases a cancellation fee may apply. You may also be charged if you fail to show up after requesting a ride. Please check out our Help Center to learn more about Saferide Technologies’ cancellation policy, including applicable fees.
						- Damage Fee. If a Driver reports that you have materially damaged the Driver's vehicle, you agree to pay a “Damage Fee” of up to TZS 1,000,000 depending on the extent of the damage (as determined by Saferide Technologies in its sole discretion), towards vehicle repair or cleaning. Saferide Technologies reserves the right (but is not obligated) to verify or otherwise require documentation of damages prior to processing the Damage Fee.
						- Tolls. In some instances tolls (or return tolls) may apply to your ride. Please see our Help Center and your market’s Saferide Technologies Cities page for more information about toll charges and a list of applicable tolls and return charges. We do not guarantee that the amount charged by Saferide Technologies will match the toll charged to the Driver, if any.<br><br>

						Other Charges. Other fees and surcharges may apply to your ride, including: actual or anticipated airport fees, provincial or local fees, or event fees as determined by Saferide Technologies or its marketing partners. In addition, where required by law Saferide Technologies will collect applicable taxes. See your market’s Saferide Technologies Cities page for details on other Charges that may apply to your ride.<br><br>

						Tips. Following a ride, you may elect to tip your Driver in cash or through the Saferide Technologies Platform. You may also elect to set a default tip amount or percentage through the Saferide Technologies App. Any tips will be provided entirely to the applicable Driver.<br><br>

						<b>4.3 General.</b><br>
						Facilitation of Charges. All Charges are facilitated through a third-party payment processor (e.g., First Data, Stripe, Inc., or Braintree, a division of PayPal, Inc.). Saferide Technologies may replace its third-party payment processor without notice to you. Charges shall only be made through the Saferide Technologies Platform. With the exception of tips, cash payments are strictly prohibited. Your payment of Charges to Saferide Technologies satisfies your payment obligation for your use of the Saferide Technologies Platform and Rideshare Services. Certain Charges may be collectively billed as a single purchase transaction to your selected payment method based on the payment frequency indicated in your settings. If you don't recognize a transaction, then check your ride receipts and payment history.<br><br>

						No Refunds. All Charges are non-refundable. This no-refund policy shall apply at all times regardless of your decision to terminate usage of the Saferide Technologies Platform, any disruption to the Saferide Technologies Platform or Rideshare Services, or any other reason whatsoever.<br><br>

						Coupons. You may receive coupons that you can apply toward payment of certain Charges upon completion of a Ride. Coupons are only valid for use on the Saferide Technologies Platform, and are not transferable or redeemable for cash except as required by law. Coupons cannot be combined unless expressly provided otherwise, and if the cost of your ride exceeds the applicable credit or discount value we will charge your payment method on file for the outstanding cost of the Ride. For quoted or variable fares, Saferide Technologies may deduct the amount attributable to the Service Fee, Tolls, or Other Charges before application of the coupon. Additional restrictions on coupons may apply as communicated to you in a relevant promotion or by clicking on the relevant coupon within the Promotions section of the Saferide Technologies App.
						Credit Card Authorization. Upon addition of a new payment method or each ride request, Saferide Technologies may seek authorization of your selected payment method to verify the payment method, ensure the ride cost will be covered, and protect against unauthorized behavior. The authorization is not a charge, however, it may reduce your available credit by the authorization amount until your bank’s next processing cycle. Should the amount of our authorization exceed the total funds on deposit in your account, you may be subject to overdraft of NSF charges by the bank issuing your debit or prepaid card. We cannot be held responsible for these charges and are unable to assist you in recovering them from your issuing bank. Check out our Help Center to learn more about our use of pre-authorization holds.<br><br>

						<b>5 Payments</b><br>
						If you are a Driver, you will receive payment for your provision of Rideshare Services pursuant to the terms of the Driver Addendum, which shall form part of this Agreement between you and Saferide Technologies.<br><br>

						<b>6. Saferide Technologies Communications</b><br>
						By entering into this Agreement or using the Saferide Technologies Platform, you agree to receive communications from us or communications related to the Saferide Technologies Platform at any of the phone numbers provided to Saferide Technologies by you or on your behalf, including via e-mail, text message, calls, and push notifications. You agree that texts, calls or prerecorded messages may be generated by automatic telephone dialing systems. Communications from Saferide Technologies, its affiliated companies and/or Drivers, may include but are not limited to: operational communications concerning your User account or use of the Saferide Technologies Platform or Rideshare Services, use of bikes and scooters through the Saferide Technologies Platform, updates concerning new and existing features on the Saferide Technologies Platform, communications concerning marketing or promotions run by us or our third-party partners, and news concerning Saferide Technologies and industry developments. If you change or deactivate the phone number you provided to Saferide Technologies, you agree to update your account information to help prevent us from inadvertently communicating with anyone who acquires your old number. Standard text messaging charges applied by your cell phone carrier will apply to text messages we send.
						IF YOU WISH TO OPT OUT OF PROMOTIONAL EMAILS, YOU CAN UNSUBSCRIBE FROM OUR PROMOTIONAL EMAIL LIST BY FOLLOWING THE UNSUBSCRIBE OPTIONS IN THE PROMOTIONAL EMAIL ITSELF. IF YOU WISH TO OPT OUT OF PROMOTIONAL CALLS OR TEXTS, YOU MAY TEXT “END” TO SAME NUMBER THAT IT CAME FROM THE MOBILE DEVICE RECEIVING THE MESSAGES. YOU ACKNOWLEDGE THAT YOU ARE NOT REQUIRED TO CONSENT TO RECEIVE PROMOTIONAL TEXTS OR CALLS AS A CONDITION OF USING THE SAFERIDE TECHNOLOGIES PLATFORM OR RELATED SERVICES. IF YOU WISH TO OPT OUT OF ALL TEXTS OR CALLS FROM SAFERIDE TECHNOLOGIES (INCLUDING OPERATIONAL OR TRANSACTIONAL TEXTS OR CALLS), YOU CAN TEXT THE WORD “STOPALL” TO SAME NUMBER THAT IT CAME FROM THE MOBILE DEVICE RECEIVING THE MESSAGES, HOWEVER YOU ACKNOWLEDGE THAT OPTING OUT OF RECEIVING ALL TEXTS MAY IMPACT YOUR USE OF THE SAFERIDE TECHNOLOGIES PLATFORM OR RELATED SERVICES.<br><br>

						<b>7. Your Information</b><br>
						Your Information is any information you provide, publish or post to or through the Saferide Technologies Platform (including any profile information you provide) or send to other Users (including via in-application feedback, any email feature, or through any Saferide Technologies-related Facebook, Twitter or other social media posting) (your “Information”). You consent to us using your Information to create a User account that will allow you to use the Saferide Technologies Platform and participate in the Rideshare Services. Our collection and use of personal information in connection with the Saferide Technologies Platform and Rideshare Services is as provided in Saferide Technologies’ Privacy Policy located at www.Saferide Technologies.com/privacy. You are solely responsible for your Information and your interactions with other members of the public, and we act only as a passive conduit for your online posting of your Information. You agree to provide and maintain accurate, current and complete information and that we and other members of the public may rely on your Information as accurate, current and complete. To enable Saferide Technologies to use your Information for the purposes described in the Privacy Policy and this Agreement, you grant to us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, transferable, sub-licensable (through multiple tiers) right and license to exercise the copyright, publicity, and database rights you have in your Information, and to use, copy, perform, display and distribute such Information to prepare derivative works, or incorporate into other works, such Information, in any media now known or not currently known. Saferide Technologies does not assert any ownership over your Information; rather, as between you and Saferide Technologies, subject to the rights granted to us in this Agreement, you retain full ownership of all of your Information and any intellectual property rights or other proprietary rights associated with your Information.<br><br>
						
						<b>8. Promotions, Referrals, and Loyalty Programs</b><br>
						Saferide Technologies, at its sole discretion, may make available promotions, referral programs and loyalty programs with different features to any Users or prospective Users. These promotions and programs, unless made to you, shall have no bearing whatsoever on your Agreement or relationship with Saferide Technologies. Saferide Technologies reserves the right to withhold or deduct credits or benefits obtained through a promotion or program in the event that Saferide Technologies determines or believes that the redemption of the promotion or receipt of the credit or benefit was in error, fraudulent, illegal, or in violation of the applicable promotion or program terms or this Agreement. Saferide Technologies reserves the right to terminate, discontinue or cancel any promotions or programs at any time and in its sole discretion without notice to you.<br><br>

						Currently, Saferide Technologies’s referral program provides you with incentives to refer your friends and family to become new Users of the Saferide Technologies Platform in your country (the “Referral Program”). Your participation in the Referral Program is subject to this Agreement and the additional Referral Program rules.<br><br>

						<b>9. Restricted Activities?</b><br>
						With respect to your use of the Saferide Technologies Platform and your participation in the Rideshare Services, you agree that you will not:<br>
						•	impersonate any person or entity;<br>
						•	stalk, threaten, or otherwise harass any person, or carry any weapons;<br>
						•	violate any law, statute, rule, permit, ordinance or regulation;<br>
						•	interfere with or disrupt the Saferide Technologies Platform or the servers or networks connected to the Saferide Technologies Platform;<br>
						•	post Information or interact on the Saferide Technologies Platform or Rideshare Services in a manner which is fraudulent, libelous, abusive, obscene, profane, sexually oriented, harassing, or illegal;<br>
						•	use the Saferide Technologies Platform in any way that infringes any third party’s rights, including: intellectual property rights, copyright, patent, trademark, trade secret or other proprietary rights or rights of publicity or privacy;<br>
						•	post, email or otherwise transmit any malicious code, files or programs designed to interrupt, damage, destroy or limit the functionality of the Saferide Technologies Platform or any computer software or hardware or telecommunications equipment or surreptitiously intercept or expropriate any system, data or personal information;<br>
						•	forge headers or otherwise manipulate identifiers in order to disguise the origin of any information transmitted through the Saferide Technologies Platform;<br>
						•	“frame” or “mirror” any part of the Saferide Technologies Platform, without our prior written authorization or use meta tags or code or other devices containing any reference to us in order to direct any person to any other web site for any purpose;<br>
						•	modify, adapt, translate, reverse engineer, decipher, decompile or otherwise disassemble any portion of the Saferide Technologies Platform;<br>
						•	rent, lease, lend, sell, redistribute, license or sublicense the Saferide Technologies Platform or access to any portion of the Saferide Technologies Platform;<br>
						•	use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, scrape, “data mine”, or in any way reproduce or circumvent the navigational structure or presentation of the Saferide Technologies Platform or its contents;<br>
						•	link directly or indirectly to any other web sites;<br>
						•	transfer or sell your User account, password and/or identification, or any other User's Information to any other party;<br>
						•	discriminate against or harass anyone on the basis of race, national origin, religion, gender, gender identity or expression, physical or mental disability, medical condition, marital status, age or sexual orientation;
						•	violate any of the Referral Program rules if you participate in the Referral Program; or<br>
						•	cause any third party to engage in the restricted activities above.<br><br>

						<b>10. Driver Representations, Warranties and Agreements</b><br>
						By providing Rideshare Services as a Driver on the Saferide Technologies Platform, you represent, warrant, and agree that:
						•	You possess a valid driver’s license and are authorized and medically fit to operate a motor vehicle and have all appropriate licenses, approvals and authority to provide transportation to Riders in all jurisdictions in which you provide Rideshare Services.<br>
						•	You own, or have the legal right to operate, the vehicle you use when providing Rideshare Services; such vehicle is in good operating condition and meets the industry safety standards and all applicable statutory and department of motor vehicle requirements for a vehicle of its kind; and any and all applicable safety recalls have been remedied per manufacturer instructions.<br>
						•	You will not engage in reckless behavior while driving, drive unsafely, operate a vehicle that is unsafe to drive, permit an unauthorized third party to accompany you in the vehicle while providing Rideshare Services, provide Services as a Driver while under the influence of alcohol or drugs, or take action that harms or threatens to harm the safety of the Saferide Technologies community or third parties.<br>
						•	You will only provide Rideshare Services using the vehicle that has been reported to, and approved by Saferide Technologies, and for which a photograph has been provided to Saferide Technologies, and you will not transport more passengers than can securely be seated in such vehicle (and no more than seven (7) passengers in any instance).<br>
						•	You will not, while providing the Rideshare Services, operate as a public or common carrier or taxi service, accept street hails, charge for rides (except as expressly provided in this Agreement), demand that a rider pay in cash, or use a credit card reader, such as a Square Reader, to accept payment or engage in any other activity in a manner that is inconsistent with your obligations under this Agreement.<br>
						•	You will not attempt to defraud Saferide Technologies or Riders on the Saferide Technologies Platform or in connection with your provision of Rideshare Services. If we suspect that you have engaged in fraudulent activity we may withhold applicable Fares or other payments for the ride(s) in question and take any other action against you available under the law.<br>
						•	You will not discriminate against Riders with disabilities and agree to review Saferide Technologies’ Anti-Discrimination Policies. You will make reasonable accommodation as required by law and our Service Animal Policy and Wheelchair Policy for Riders who travel with their service animals or who use wheelchairs (or other mobility devices) that can be folded for safe and secure storage in the car’s trunk or backseat.<br>
						•	You agree that we may obtain information about you, including your criminal and driving records, and you agree to provide any further necessary authorizations to facilitate our access to such records during the term of the Agreement.
						•	You have a valid policy of liability insurance (in coverage amounts consistent with all applicable legal requirements) that names or schedules you for the operation of the vehicle you use to provide Rideshare Services.
						•	You will pay ALL applicable taxes based on your provision of Rideshare Services and any payments received by you.<br><br>


						<b>11. Intellectual Property</b><br>
						All intellectual property rights in the Saferide Technologies Platform shall be owned by Saferide Technologies absolutely and in their entirety. These rights include database rights, copyright, design rights (whether registered or unregistered), trademarks (whether registered or unregistered) and other similar rights wherever existing in the world together with the right to apply for protection of the same. All other trademarks, logos, service marks, company or product names set forth in the Saferide Technologies Platform are the property of their respective owners. You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information (“Submissions”) provided by you to us are non-confidential and shall become the sole property of Saferide Technologies. Saferide Technologies shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.<br><br>

						SAFERIDE TECHNOLOGIES and other Saferide Technologies logos, designs, graphics, icons, scripts and service names are registered trademarks, trademarks or trade dress of Saferide Technologies in the Republic of South Africa and/or other countries (collectively, the “Saferide Technologies Marks”). If you provide Rideshare Services as a Driver, Saferide Technologies grants to you, during the term of this Agreement, and subject to your compliance with the terms and conditions of this Agreement, a limited, revocable, non-exclusive license to display and use the Saferide Technologies Marks solely on the Saferide Technologies stickers/decals, Saferide Technologies Amp, and any other Saferide Technologies-branded items provided by Saferide Technologies directly to you in connection with providing the Rideshare Services (“License”). The License is non-transferable and non-assignable, and you shall not grant to any third party any right, permission, license or sublicense with respect to any of the rights granted hereunder without Saferide Technologies’ prior written permission, which it may withhold in its sole discretion. The Saferide Technologies logo (or any Saferide Technologies Marks) may not be used in any manner that is likely to cause confusion, including but not limited to: use of a Saferide Technologies Mark in a domain name or Saferide Technologies referral code, or use of a Saferide Technologies Mark as a social media handle or name, avatar, profile photo, icon, favicon, or banner. You may identify yourself as a Driver on the Saferide Technologies Platform, but may not misidentify yourself as Saferide Technologies, an employee of Saferide Technologies, or a representative of Saferide Technologies.<br><br>

						You acknowledge that Saferide Technologies is the owner and licensor of the Saferide Technologies Marks, including all goodwill associated therewith, and that your use of the Saferide Technologies logo (or any Saferide Technologies Marks) will confer no interest in or ownership of the Saferide Technologies Marks in you but rather inures to the benefit of Saferide Technologies. You agree to use the Saferide Technologies logo strictly in accordance with Saferide Technologies’ Brand Guidelines, as may be provided to you and revised from time to time, and to immediately cease any use that Saferide Technologies determines to nonconforming or otherwise unacceptable.<br><br>

						You agree that you will not: (1) create any materials that use the Saferide Technologies Marks or any derivatives of the Saferide Technologies Marks as a trademark, service mark, trade name or trade dress, other than as expressly approved by Saferide Technologies in writing; (2) use the Saferide Technologies Marks in any way that tends to impair their validity as proprietary trademarks, service marks, trade names or trade dress, or use the Saferide Technologies Marks other than in accordance with the terms, conditions and restrictions herein; (3) take any other action that would jeopardize or impair Saferide Technologies’ rights as owner of the Saferide Technologies Marks or the legality and/or enforceability of the Saferide Technologies Marks, including, challenging or opposing Saferide Technologies’ ownership in the Saferide Technologies Marks; (4) apply for trademark registration or renewal of trademark registration of any of the Saferide Technologies Marks, any derivative of the Saferide Technologies Marks, any combination of the Saferide Technologies Marks and any other name, or any trademark, service mark, trade name, symbol or word which is similar to the Saferide Technologies Marks; (5) use the Saferide Technologies Marks on or in connection with any product, service or activity that is in violation of any law, statute, government regulation or standard.<br><br>

						You agree you will not rent, lease, lend, sell, or otherwise redistribute the Saferide Technologies driver amp, or manufacture, produce, print, sell, distribute, purchase, or display counterfeit/inauthentic Saferide Technologies driver amps or other Saferide Technologies Marks or (including but not limited to signage, stickers, apparel, or decals) from any source other than directly from Saferide Technologies.<br><br>
						Violation of any provision of this License may result in immediate termination of the License, in Saferide Technologies’ sole discretion, a takedown request sent to the appropriate ISP, or social media platform, and/or a Uniform Domain-Name Dispute-Resolution Policy Proceeding (or equivalent proceeding). If you create any materials (physical or digital) bearing the Saferide Technologies Marks (in violation of this Agreement or otherwise), you agree that upon their creation Saferide Technologies exclusively owns all right, title and interest in and to such materials, including any modifications to the Saferide Technologies Marks or derivative works based on the Saferide Technologies Marks or Saferide Technologies copyrights. You further agree to assign any interest or right you may have in such materials to Saferide Technologies, and to provide information and execute any documents as reasonably requested by Saferide Technologies to enable Saferide Technologies to formalize such assignment.<br><br>

						Saferide Technologies respects the intellectual property of others, and expects Users to do the same. If you believe, in good faith, that any materials on the Saferide Technologies Platform infringe upon your copyrights, please view our Copyright Policy for information on how to make a copyright complaint.<br><br>

						<b>12. Disclaimers</b><br>
						The following disclaimers are made on behalf of Saferide Technologies, our affiliates, subsidiaries, parents, successors and assigns, and each of our respective officers, directors, employees, agents, and shareholders.
						Saferide Technologies does not provide transportation services, and Saferide Technologies is not a transportation carrier. Saferide Technologies is not a common carrier or public carrier. It is up to the Driver to decide whether or not to offer a ride to a Rider contacted through the Saferide Technologies Platform, and it is up to the Rider to decide whether or not to accept a ride from any Driver contacted through the Saferide Technologies Platform. We cannot ensure that a Driver or Rider will complete an arranged transportation service. We have no control over the quality or safety of the transportation that occurs as a result of the Rideshare Services.<br><br>

						The Saferide Technologies Platform is provided on an “as is” basis and without any warranty or condition, express, implied or statutory. We do not guarantee and do not promise any specific results from use of the Saferide Technologies Platform and/or the Rideshare Services, including the ability to provide or receive Rideshare Services at any given location or time. Saferide Technologies reserves the right, for example, to limit or eliminate access to the Saferide Technologies Platform for Rideshare Services in specific geographic areas and/or at specific times based on commercial viability, public health concerns, or changes in law. To the fullest extent permitted by law, we specifically disclaim any implied warranties of title, merchantability, fitness for a particular purpose and non-infringement.<br><br>

						We do not warrant that your use of the Saferide Technologies Platform or Rideshare Services will be accurate, complete, reliable, current, secure, uninterrupted, always available, or error-free, or will meet your requirements, that any defects in the Saferide Technologies Platform will be corrected, or that the Saferide Technologies Platform is free of viruses or other harmful components. We disclaim liability for, and no warranty is made with respect to, connectivity and availability of the Saferide Technologies Platform or Rideshare Services.<br><br>

						We cannot guarantee that each Rider or Driver is who he or she claims to be. Please use common sense when using the Saferide Technologies Platform and Rideshare Services, including looking at the photos of the Driver or Rider you have matched with to make sure it is the same individual you see in person. Please note that there are also risks of dealing with underage persons or people acting under false pretense, and we do not accept responsibility or liability for any content, communication or other use or access of the Saferide Technologies Platform by persons under the age of 18 in violation of this Agreement. We encourage you to communicate directly with each potential Driver or Rider prior to engaging in an arranged transportation service.<br><br>

						Saferide Technologies is not responsible for the conduct, whether online or offline, of any User of the Saferide Technologies Platform or Rideshare Services. You are solely responsible for your interactions with other Users. We do not procure insurance for, nor are we responsible for, personal belongings left in the car by Drivers or Riders. By using the Saferide Technologies Platform and participating in the Rideshare Services, you agree to accept such risks and agree that Saferide Technologies is not responsible for the acts or omissions of Users on the Saferide Technologies Platform or participating in the Rideshare Services.<br><br>

						You are responsible for the use of your User account and Saferide Technologies expressly disclaims any liability arising from the unauthorized use of your User account. Should you suspect that any unauthorized party may be using your User account or you suspect any other breach of security, you agree to notify us immediately<br><br>

						It is possible for others to obtain information about you that you provide, publish or post to or through the Saferide Technologies Platform (including any profile information you provide), send to other Users, or share during the Rideshare Services, and to use such information to harass or harm you. We are not responsible for the use of any personal information that you disclose to other Users on the Saferide Technologies Platform or through the Rideshare Services. Please carefully select the type of information that you post on the Saferide Technologies Platform or through the Rideshare Services or release to others. We disclaim all liability, regardless of the form of action, for the acts or omissions of other Users (including unauthorized users, or “hackers”).<br><br>

						Opinions, advice, statements, offers, or other information or content concerning Saferide Technologies or made available through the Saferide Technologies Platform, but not directly by us, are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content. Under no circumstances will we be responsible for any loss or damage resulting from your reliance on information or other content posted by third parties, whether on the Saferide Technologies Platform or otherwise. We reserve the right, but we have no obligation, to monitor the materials posted on the Saferide Technologies Platform and remove any such material that in our sole opinion violates, or is alleged to violate, the law or this agreement or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of Users or others.<br><br>

						Location data provided by the Saferide Technologies Platform is for basic location purposes only and is not intended to be relied upon in situations where precise location information is needed or where erroneous, inaccurate or incomplete location data may lead to death, personal injury, property or environmental damage. Neither Saferide Technologies, nor any of its content providers, guarantees the availability, accuracy, completeness, reliability, or timeliness of location data tracked or displayed by the Saferide Technologies Platform. Any of your Information, including geolocational data, you upload, provide, or post on the Saferide Technologies Platform may be accessible to Saferide Technologies and certain Users of the Saferide Technologies Platform.<br><br>

						Saferide Technologies advises you to use the Saferide Technologies Platform with a data plan with unlimited or very high data usage limits, and Saferide Technologies shall not be responsible or liable for any fees, costs, or overage charges associated with any data plan you use to access the Saferide Technologies Platform.<br><br>

						This paragraph applies to any version of the Saferide Technologies Platform that you acquire from the Apple App Store. This Agreement is entered into between you and Saferide Technologies. Apple, Inc. (“Apple”) is not a party to this Agreement and shall have no obligations with respect to the Saferide Technologies Platform. Saferide Technologies, not Apple, is solely responsible for the Saferide Technologies Platform and the content thereof as set forth hereunder. However, Apple and Apple’s subsidiaries are third-party beneficiaries of this Agreement. Upon your acceptance of this Agreement, Apple shall have the right (and will be deemed to have accepted the right) to enforce this Agreement against you as a third-party beneficiary thereof. This Agreement incorporates by reference Apple’s Licensed Application End User License Agreement, for purposes of which, you are “the end-user.” In the event of a conflict in the terms of the Licensed Application End User License Agreement and this Agreement, the terms of this Agreement shall control.<br><br>

						As a Driver, you may be able to use "Saferide Technologies Nav built by Google" while providing Rideshare Services on the Platform. Riders and Drivers may also use Google Maps while using the Saferide Technologies App. In either case, you agree that Google may collect your location data when the Saferide Technologies App is running in order to provide and improve Google's services that such data may also be shared with Saferide Technologies in order to improve its operations, and that Google's terms and privacy policy will apply to this usage.<br><br>

						Saferide Technologies shall not be in breach of this Agreement nor liable for failure or delay in performing obligations under this Agreement if such failure or delay results from events, circumstances or causes beyond its reasonable control including (without limitation) natural disasters or acts of God; acts of terrorism; labor disputes or stoppages; war; government action; epidemic or pandemic; chemical or biological contamination; strikes, riots, or acts of domestic or international terrorism; quarantines; national or regional emergencies; or any other cause, whether similar in kind to the foregoing or otherwise, beyond the party’s reasonable control. All service dates under this Agreement affected by force majeure shall be tolled for the duration of such force majeure. The parties hereby agree, when feasible, not to cancel but reschedule the pertinent obligations as soon as practicable after the force majeure condition ceases to exist.<br><br>

						<b>13. Indemnity</b><br>
						You will defend, indemnify, and hold Saferide Technologies including our affiliates, subsidiaries, parents, successors and assigns, and each of our respective officers, directors, employees, agents, or shareholders harmless from any claims, actions, suits, losses, costs, liabilities and expenses (including reasonable attorneys’ fees) relating to or arising out of your use of the Saferide Technologies Platform and participation in the Rideshare Services, including: (1) your breach of this Agreement or the documents it incorporates by reference; (2) your violation of any law or the rights of a third party, including, Drivers, Riders, other motorists, and pedestrians, as a result of your own interaction with such third party; (3) any allegation that any materials that you submit to us or transmit through the Saferide Technologies Platform or to us infringe or otherwise violate the copyright, trademark, trade secret or other intellectual property or other rights of any third party; (4) your ownership, use or operation of a motor vehicle or passenger vehicle, including your provision of Rideshare Services as a Driver; and/or (5) any other activities in connection with the Rideshare Services. This indemnity shall be applicable without regard to the negligence of any party, including any indemnified person.<br><br>

						<b>14. Limitation of Liability</b><br>
						IN NO EVENT WILL SAFERIDE TECHNOLOGIES, INCLUDING OUR AFFILIATES, SUBSIDIARIES, PARENTS, SUCCESSORS AND ASSIGNS, AND EACH OF OUR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR SHAREHOLDERS (COLLECTIVELY “SAFERIDE TECHNOLOGIES” FOR PURPOSES OF THIS SECTION), BE LIABLE TO YOU FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, CONSEQUENTIAL, OR INDIRECT DAMAGES (INCLUDING DAMAGES FOR DELETION, CORRUPTION, LOSS OF DATA, LOSS OF PROGRAMS, FAILURE TO STORE ANY INFORMATION OR OTHER CONTENT MAINTAINED OR TRANSMITTED BY THE SAFERIDE TECHNOLOGIES PLATFORM, SERVICE INTERRUPTIONS, OR FOR THE COST OF PROCUREMENT OF SUBSTITUTE SERVICES) ARISING OUT OF OR IN CONNECTION WITH THE SAFERIDE TECHNOLOGIES PLATFORM, RIDESHARE SERVICES, OR THIS AGREEMENT, HOWEVER ARISING INCLUDING NEGLIGENCE, EVEN IF WE OR OUR AGENTS OR REPRESENTATIVES KNOW OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE SAFERIDE TECHNOLOGIES PLATFORM MAY BE USED BY YOU TO REQUEST AND SCHEDULE TRANSPORTATION, GOODS, OR OTHER SERVICES WITH THIRD-PARTY PROVIDERS, BUT YOU AGREE THAT SAFERIDE TECHNOLOGIES HAS NO RESPONSIBILITY OR LIABILITY TO YOU RELATED TO ANY TRANSPORTATION, GOODS OR OTHER SERVICES PROVIDED TO YOU BY THIRD PARTY PROVIDERS OTHER THAN AS EXPRESSLY SET FORTH IN IN THIS AGREEMENT. CERTAIN JURISDICTIONS MAY NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.<br><br>

						<b>15. Term and Termination</b><br>
						This Agreement is effective upon your acceptance of this Agreement. This Agreement may be terminated: a) by User, without cause, upon seven (7) days’ prior written notice to Saferide Technologies; or b) by either Party immediately, without notice, upon the other Party’s material breach of this Agreement, including but not limited to any breach of Section 9 or breach of Section 10(a) through (i) of this Agreement. In addition, Saferide Technologies may terminate this Agreement or deactivate your User account immediately in the event: (1) you no longer qualify to provide Rideshare Services or to operate the approved vehicle under applicable law, rule, permit, ordinance or regulation; (2) you fall below Saferide Technologies’ star rating or cancellation threshold; (3) Saferide Technologies has the good faith belief that such action is necessary to protect the safety of the Saferide Technologies community or third parties, provided that in the event of a deactivation pursuant to (1)-(3) above, you will be given notice of the potential or actual deactivation and an opportunity to attempt to cure the issue to Saferide Technologies’ reasonable satisfaction prior to Saferide Technologies permanently terminating the Agreement. For all other breaches of this Agreement, you will be provided notice and an opportunity to cure the breach. If the breach is cured in a timely manner and to Saferide Technologies’ satisfaction, this Agreement will not be permanently terminated. Sections 2, 6, 7 (with respect to the license), 11-12, 14-19, and 21 shall survive any termination or expiration of this Agreement.<br><br>

						<b>16. DISPUTE RESOLUTION AND ARBITRATION AGREEMENT</b><br>
						(a) Agreement to Binding Arbitration Between You and Saferide Technologies.
						YOU AND SAFERIDE TECHNOLOGIES MUTUALLY AGREE TO WAIVE OUR RESPECTIVE RIGHTS TO RESOLUTION OF DISPUTES IN A COURT OF LAW BY A JUDGE OR JURY AND AGREE TO RESOLVE ANY DISPUTE BY ARBITRATION, as set forth below. BY AGREEING TO ARBITRATION, YOU UNDERSTAND THAT YOU AND SAFERIDE TECHNOLOGIES ARE WAIVING THE RIGHT TO SUE IN COURT OR HAVE A JURY TRIAL FOR ALL CLAIMS, EXCEPT AS EXPRESSLY OTHERWISE PROVIDED IN THIS ARBITRATION AGREEMENT. This Agreement is intended to require arbitration of every claim or dispute that can lawfully be arbitrated, except for those claims and disputes which by the terms of this Arbitration Agreement are expressly excluded from the requirement to arbitrate.<br><br>

						(b) Prohibition of Class Actions and Non-Individualized Relief.
						YOU UNDERSTAND AND AGREE THAT YOU AND SAFERIDE TECHNOLOGIES MAY EACH BRING CLAIMS IN ARBITRATION AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY AND NOT ON A CLASS, COLLECTIVE ACTION, OR REPRESENTATIVE BASIS (“CLASS ACTION WAIVER”). YOU UNDERSTAND AND AGREE THAT YOU AND SAFERIDE TECHNOLOGIES BOTH ARE WAIVING THE RIGHT TO PURSUE OR HAVE A DISPUTE RESOLVED AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE OR REPRESENTATIVE PROCEEDING. <br><br>

						<b>17. Confidentiality</b><br>
						You agree not to use any technical, financial, strategic and other proprietary and confidential information relating to Saferide Technologies’ business, operations and properties, information about a User made available to you in connection with such User’s use of the Platform, which may include the User’s name, pick-up location, contact information and photo (“Confidential Information”) disclosed to you by Saferide Technologies for your own use or for any purpose other than as contemplated herein. You shall not disclose or permit disclosure of any Confidential Information to third parties, and you agree not to store separate and outside of the Saferide Technologies Platform any User Information obtained from the Saferide Technologies Platform. You agree to take all reasonable measures to protect the secrecy of and avoid disclosure or use of Confidential Information of Saferide Technologies in order to prevent it from falling into the public domain. Notwithstanding the above, you shall not have liability to Saferide Technologies with regard to any Confidential Information which you can prove: was in the public domain at the time it was disclosed by Saferide Technologies or has entered the public domain through no fault of yours; was known to you, without restriction, at the time of disclosure, as demonstrated by files in existence at the time of disclosure; is disclosed with the prior written approval of Saferide Technologies; becomes known to you, without restriction, from a source other than Saferide Technologies without breach of this Agreement by you and otherwise not in violation of Saferide Technologies’ rights; or is disclosed pursuant to the order or requirement of a court, administrative agency, or other governmental body; provided, however, that You shall provide prompt notice of such court order or requirement to Saferide Technologies to enable Saferide Technologies to seek a protective order or otherwise prevent or restrict such disclosure.<br><br>

						<b>18. Relationship with Saferide Technologies</b><br>
						As a Driver on the Saferide Technologies Platform, you acknowledge and agree that you and Saferide Technologies are in a direct business relationship, and the relationship between the parties under this Agreement is solely that of independent contracting parties. You and Saferide Technologies expressly agree that (1) this is not an employment agreement and does not create an employment relationship between you and Saferide Technologies; and (2) no joint venture, franchisor-franchisee, partnership, or agency relationship is intended or created by this Agreement. You have no authority to bind Saferide Technologies, and you undertake not to hold yourself out as an employee, agent or authorized representative of Saferide Technologies.<br><br>

						Saferide Technologies does not, and shall not be deemed to, direct or control you generally or in your performance under this Agreement specifically, including in connection with your provision of Rideshare Services, your acts or omissions, or your operation and maintenance of your vehicle. You retain the sole right to determine when, where, and for how long you will utilize the Saferide Technologies Platform. Saferide Technologies does not, and shall not be deemed to, unilaterally prescribe specific dates, times of day, or any minimum number of hours for you to utilize the Saferide Technologies Platform. You retain the option to accept or to decline or ignore a Rider’s request for Rideshare Services via the Saferide Technologies Platform, or to cancel an accepted request for Rideshare Services via the Saferide Technologies Platform, subject to Saferide Technologies’ then-current cancellation policies. Saferide Technologies does not, and shall not be deemed to, require you to accept any specific request for Rideshare Services as a condition of maintaining access to the platform. With the exception of any signage required by law or permit/license rules or requirements, Saferide Technologies shall have no right to require you to: (a) display Saferide Technologies’ names, logos or colors on your vehicle(s); or (b) wear a uniform or any other clothing displaying Saferide Technologies’ names, logos or colors. You acknowledge and agree that you have complete discretion to provide Rideshare Services or otherwise engage in any other business or employment activities, including but not limited to providing services similar to the Rideshare Services to other companies, and that Saferide Technologies does not, and shall not be deemed to, restrict you from engaging in any such activity.<br><br>

						<b>19. General</b><br>
						Except as provided in Section 16, this Agreement shall be governed by the laws of the Republic of South Africa without regard to choice of law principles. This choice of law provision is only intended to specify the use of South African law to interpret this Agreement and is not intended to create any other substantive right to non-South Africans to assert claims under South African law whether by statute, common law, or otherwise. If any provision of this Agreement is or becomes invalid or non- binding, the parties shall remain bound by all other provisions of this Agreement. In that event, the parties shall replace the invalid or non-binding provision with provisions that are valid and binding and that have, to the greatest extent possible, a similar effect as the invalid or non-binding provision, given the contents and purpose of this Agreement. You agree that this Agreement and all incorporated agreements may be automatically assigned by Saferide Technologies, in our sole discretion by providing notice to you. Except as explicitly stated otherwise, any notices to Saferide Technologies shall be given by certified mail, postage prepaid and return receipt requested to Saferide Technologies, Inc., [Enter Business Address]. Any notices to you shall be provided to you through the Saferide Technologies Platform or given to you via the email address or physical you provide to Saferide Technologies during the registration process. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. The words “include”, “includes” and “including” are deemed to be followed by the words “without limitation”. A party’s failure to act with respect to a breach by the other party does not constitute a waiver of the party’s right to act with respect to subsequent or similar breaches. This Agreement sets forth the entire understanding and agreement between you and Saferide Technologies with respect to the subject matter hereof and supersedes all previous understandings and agreements between the parties, whether oral or written.<br><br>

					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<?php include ('inc/footer.php');?>